version: '3'

services:

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: production-ready-pipelines-gitlab
    hostname: 'localhost'
    environment:
      GITLAB_ROOT_PASSWORD: 5x3(^[!X<Iq'l0M2
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
    ports:
      - '80:80'
      - '22:22'
    volumes:
      - './.gitlab/config:/etc/gitlab'
      - './.gitlab/logs:/var/log/gitlab'
      - './.gitlab/data:/var/opt/gitlab'

  gitlab-runner:
    image: 'gitlab/gitlab-runner:latest'
    container_name: production-ready-pipelines-gitlab-runner
    volumes:
      - './.gitlab-runner/config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'